In [1]:
import pandas as pd
import numpy as np
import json

In [32]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows',50)

In [3]:
# reading in yelp data

yelp_business_alt = pd.read_json('/Users/EBled1/Springboard DS/Springboard/Capstone Two/Capstone Two/data/raw/yelp_dataset/yelp_academic_dataset_business.json', lines = True)

In [4]:
yelp_business_alt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160585 entries, 0 to 160584
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   160585 non-null  object
 1   name          160585 non-null  object
 2   address       160585 non-null  object
 3   city          160585 non-null  object
 4   state         160585 non-null  object
 5   postal_code   160585 non-null  object
 6   latitude      160585 non-null  float64
 7   longitude     160585 non-null  float64
 8   stars         160585 non-null  float64
 9   review_count  160585 non-null  int64
 10  is_open       160585 non-null  int64
 11  attributes    145593 non-null  object
 12  categories    160470 non-null  object
 13  hours         133244 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 17.2+ MB

In [5]:
# seeing what states are most represented

yelp_business_alt.state.value_counts()

MA     36012
OR     25175
TX     24485
FL     21907
GA     18090
BC     17298
OH     11258
CO      3198
WA      3121
CA        13
NH         4
NY         2
AZ         2
VA         2
ON         2
WY         1
KS         1
OK         1
MN         1
ABE        1
KY         1
WI         1
DC         1
NM         1
HI         1
ME         1
AL         1
IL         1
NC         1
DE         1
MI         1
Name: state, dtype: int64

In [7]:
print(yelp_business_alt.columns)
yelp_business_alt.categories.unique().tolist()[0:5]

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours'],
      dtype='object')

['Gastropubs, Food, Beer Gardens, Restaurants, Bars, American (Traditional), Beer Bar, Nightlife, Breweries',
 'Salad, Soup, Sandwiches, Delis, Restaurants, Cafes, Vegetarian',
 'Antiques, Fashion, Used, Vintage & Consignment, Shopping, Furniture Stores, Home & Garden',
 'Beauty & Spas, Hair Salons',
 'Gyms, Active Life, Interval Training Gyms, Fitness & Instruction']

In [12]:
# looking the size step-down when filtering for relevant records

print(yelp_business_alt.shape)
print(yelp_business_alt.loc[(yelp_business_alt.state == 'TX')].shape)
print(yelp_business_alt.loc[(yelp_business_alt.state == 'TX') & (yelp_business_alt['categories'].str.contains('Restaurant'))].shape)

(160585, 14)
(24485, 14)
(5452, 14)

In [13]:
# reducing yelp data to Texas restaurants only

yelp_tx = yelp_business_alt.loc[(yelp_business_alt.state == 'TX') & (yelp_business_alt['categories'].str.contains('Restaurant'))].sort_values(by=['name'])
yelp_tx.address = yelp_tx.address.str.upper()
yelp_tx.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
77606,sS25ybHXWdkdhcUhfkWJxQ,# 19,1112 E 6TH ST,Austin,TX,78702,30.264840,-97.730867,4.5,18,0,"{'RestaurantsAttire': 'u'casual'', 'Ambience':...","Food, Restaurants, Sandwiches","{'Tuesday': '19:0-22:0', 'Wednesday': '19:0-22..."
56196,248ccWwT6bFbR6am5w391A,100 Pizzitas,900 E 7TH ST,Austin,TX,78702,30.266555,-97.733032,4.0,75,0,"{'HasTV': 'True', 'BusinessAcceptsCreditCards'...","Spanish, Pizza, Restaurants, Mediterranean","{'Tuesday': '11:30-22:0', 'Wednesday': '11:30-..."
56947,G50RJhfZgaVqnKEWrjD_Aw,1000 Degrees Neapolitan Pizzeria,"10515 N MOPAC EXPY, STE A120",Austin,TX,78757,30.389495,-97.732481,4.0,52,0,"{'GoodForMeal': '{'dessert': False, 'latenight...","Italian, Restaurants, Pizza","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
60724,6uSPLo9R0vxtJxPIhsMSMg,101 By Teahaus,"6929 AIRPORT BLVD, STE 132",Austin,TX,78752,30.337121,-97.716716,4.0,256,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Bubble Tea, Restaurants, Coffee & Tea, Asian F...","{'Monday': '11:30-20:0', 'Tuesday': '11:30-20:..."
159663,a4RvgJWV2wd2DeogFE85_w,11th Street Station,"1050 E 11TH ST, STE 100",Austin,TX,78702,30.269190,-97.729194,3.0,39,0,"{'WiFi': 'u'no'', 'RestaurantsGoodForGroups': ...","Restaurants, Soul Food, Southern",None

In [119]:
yelp_tx.shape

(5452, 14)

In [87]:
yelp_tx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5444 entries, 77606 to 42299
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   5444 non-null   object
 1   name          5444 non-null   object
 2   address       5444 non-null   object
 3   city          5444 non-null   object
 4   state         5444 non-null   object
 5   postal_code   5444 non-null   object
 6   latitude      5444 non-null   float64
 7   longitude     5444 non-null   float64
 8   stars         5444 non-null   float64
 9   review_count  5444 non-null   int64
 10  is_open       5444 non-null   int64
 11  attributes    5393 non-null   object
 12  categories    5444 non-null   object
 13  hours         4664 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 638.0+ KB

In [14]:
yelp_tx.latitude = str(yelp_tx.latitude)
yelp_tx.longitude = str(yelp_tx.longitude)
#yelp_tx.info()

In [15]:
# seeing what Texas city are most represented

yelp_tx.city.value_counts(normalize=True)

Austin                  0.910492
Buda                    0.013023
Bee Cave                0.012106
Kyle                    0.011922
Lakeway                 0.011372
Dripping Springs        0.010271
Manor                   0.006053
Pflugerville            0.006053
Sunset Valley           0.004219
West Lake Hills         0.003852
Del Valle               0.003118
Manchaca                0.001651
Driftwood               0.000734
AUSTIN                  0.000550
Volente                 0.000367
Bee Caves               0.000367
Rollingwood             0.000367
Point Venture           0.000367
Leander                 0.000367
Spicewood               0.000367
North Lamar             0.000183
San Marcos              0.000183
Garfield                0.000183
Lago Vista              0.000183
Creedmoor               0.000183
Oakhill                 0.000183
Niederwald              0.000183
Thoroughbred Estates    0.000183
Dallas                  0.000183
Jackson                 0.000183
Beecave                 0.000183
Austin texas            0.000183
Pilot Knob Acres        0.000183
Name: city, dtype: float64

In [16]:
# reading in Austin restaurant inspections data

austin_inspections = pd.read_csv('/Users/EBled1/Springboard DS/Springboard/Capstone Two/Capstone Two/data/raw/austin_restaurant_inspections.csv')

In [17]:
austin_inspections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25393 entries, 0 to 25392
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Restaurant Name      25393 non-null  object
 1   Zip Code             25385 non-null  float64
 2   Inspection Date      25393 non-null  object
 3   Score                25393 non-null  int64
 4   Address              25391 non-null  object
 5   Facility ID          25393 non-null  int64
 6   Process Description  25393 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.4+ MB

In [18]:
austin_inspections.sort_values(by=['Restaurant Name','Inspection Date']).head(20)

# looks why we have a time series for many restaurants for various inspections

,Restaurant Name,Zip Code,Inspection Date,Score,Address,Facility ID,Process Description
2362,"""CB",78701.0,01/02/2020,96,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection
17494,"""CB",78701.0,03/08/2018,99,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection
23397,"""CB",78701.0,08/05/2019,95,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection
11497,"""CB",78701.0,09/05/2018,95,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection
6705,"""CB",78701.0,11/17/2020,97,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection
17165,'Bout Time II,78752.0,03/02/2020,83,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection
19,'Bout Time II,78752.0,06/05/2018,83,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection
9538,'Bout Time II,78752.0,07/25/2019,77,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection
7528,1-Stop Food Store,78751.0,06/27/2018,94,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection
15141,1-Stop Food Store,78751.0,12/05/2018,93,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection
21079,1-Stop Food Store,78751.0,12/12/2019,96,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection
24084,1-Stop Food Store,78751.0,12/16/2020,97,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection
16354,101 by Tea Haus LLC,78752.0,01/07/2020,94,"6929 AIRPORT BLVD\nAUSTIN, TX 78752\n(30.33649...",11785910,Routine Inspection
2882,101 by Tea Haus LLC,78752.0,04/30/2019,93,"6929 AIRPORT BLVD\nAUSTIN, TX 78752\n(30.33649...",11785910,Routine Inspection
22268,101 by Tea Haus LLC,78752.0,06/22/2020,97,"6929 AIRPORT BLVD\nAUSTIN, TX 78752\n(30.33649...",11785910,Routine Inspection
10360,101 by Tea Haus LLC,78752.0,08/15/2019,96,"6929 AIRPORT BLVD\nAUSTIN, TX 78752\n(30.33649...",11785910,Routine Inspection
20773,101 by Tea Haus LLC,78752.0,10/24/2018,87,"6929 AIRPORT BLVD\nAUSTIN, TX 78752\n(30.33649...",11785910,Routine Inspection
23627,11 Degrees Daiquiri,78660.0,01/10/2019,98,"2700 W PECAN ST\nAUSTIN, TX 78660\n(30.449334,...",11958735,Routine Inspection
8142,11 Degrees Daiquiri,78660.0,01/13/2020,90,"2700 W PECAN ST\nAUSTIN, TX 78660\n(30.449334,...",11958735,Routine Inspection
8503,11 Degrees Daiquiri,78660.0,11/18/2020,97,"2700 W PECAN ST\nAUSTIN, TX 78660\n(30.449334,...",11958735,Routine Inspection

In [19]:
# binning numeric scores by letter grade
# move this to appropriate directory for storing functions and read the function in from there

def letter_grade(row):
    if row['Score'] >= 90:
        return 'A'
    if row['Score'] >= 80:
        return 'B'
    if row['Score'] >= 70:
        return 'C'
    return 'F'

In [20]:
austin_inspections['letter_grade'] = austin_inspections.apply (lambda row: letter_grade(row), axis=1)
# laustin_inspections.sort_values(by=['Restaurant Name']).head(10)

,Restaurant Name,Zip Code,Inspection Date,Score,Address,Facility ID,Process Description,letter_grade
11497,"""CB",78701.0,09/05/2018,95,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection,A
6705,"""CB",78701.0,11/17/2020,97,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection,A
23397,"""CB",78701.0,08/05/2019,95,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection,A
17494,"""CB",78701.0,03/08/2018,99,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection,A
2362,"""CB",78701.0,01/02/2020,96,"809 RED RIVER ST\nAUSTIN, TX 78701\n(30.269075...",11070017,Routine Inspection,A
17165,'Bout Time II,78752.0,03/02/2020,83,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection,B
9538,'Bout Time II,78752.0,07/25/2019,77,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection,C
19,'Bout Time II,78752.0,06/05/2018,83,"6607 N IH\nAUSTIN, TX 78752",10830983,Routine Inspection,B
21079,1-Stop Food Store,78751.0,12/12/2019,96,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection,A
7528,1-Stop Food Store,78751.0,06/27/2018,94,"5101 AIRPORT BLVD\nAUSTIN, TX 78751\n(30.31236...",10632697,Routine Inspection,A

In [21]:
# looking at distribution of records by letter grade

austin_inspections.letter_grade.value_counts(normalize=True)

A    0.696176
B    0.239909
C    0.058638
F    0.005277
Name: letter_grade, dtype: float64

In [22]:
#austin_inspections.Address

In [23]:
# extracting a cleaner address line item for merge

austin_inspections['addr_line_1'] = (austin_inspections['Address'].str.split('\n').str[0].str.upper())
austin_inspections.head(1)

,Restaurant Name,Zip Code,Inspection Date,Score,Address,Facility ID,Process Description,letter_grade,addr_line_1
0,Austin Golf Club,78669.0,08/15/2018,100,"24900 W SH\nSPICEWOOD, TX 78669",2801719,Routine Inspection,A,24900 W SH

In [24]:
# converting 'Zip Code' from float to string for merge

austin_inspections['Zip Code'] = (austin_inspections['Zip Code'].fillna(0).apply(np.int64)).apply(str)

In [25]:
austin_inspections.head(1)

,Restaurant Name,Zip Code,Inspection Date,Score,Address,Facility ID,Process Description,letter_grade,addr_line_1
0,Austin Golf Club,78669,08/15/2018,100,"24900 W SH\nSPICEWOOD, TX 78669",2801719,Routine Inspection,A,24900 W SH

In [28]:
austin_inspections['Restaurant Name'] = austin_inspections['Restaurant Name'].str.upper()
yelp_tx['name'] = yelp_tx['name'].str.upper()

In [30]:
#join inspections and yelp data

print(austin_inspections.shape)
austin_inspections_yelp = austin_inspections.merge(yelp_tx, how='left', left_on =['addr_line_1'], right_on =['address'],
                        suffixes = ('','_yelp'))
print(austin_inspections_yelp.shape)

# increased row count from join is addressed in subsequent filtering

(25393, 9)
(36272, 23)

In [31]:
#austin_inspections_yelp.head()

In [33]:
# checking out records that matched

print(len(austin_inspections_yelp))
print(len(austin_inspections_yelp.loc[austin_inspections_yelp.business_id.isna()==True]))
austin_inspections_yelp[['Restaurant Name','name']].loc[austin_inspections_yelp.business_id.isna()==False].head(10)

36272
14999

              Restaurant Name                       name
25  FRESA'S CHICKEN AL CARBON  FRESA'S CHICKEN AL CARBON
27       OOB-ABIA - VINO VOLO                   24 DINER
28       OOB-ABIA - VINO VOLO      FARA CAFÉ COFFEE SHOP
29       OOB-ABIA - VINO VOLO                 FIG + PLUM
30       OOB-ABIA - VINO VOLO                HILL'S CAFE
31       OOB-ABIA - VINO VOLO    HOOVER'S CHICKEN & MORE
32       OOB-ABIA - VINO VOLO           HUT’S HAMBURGERS
33       OOB-ABIA - VINO VOLO                     I VINI
34       OOB-ABIA - VINO VOLO       LEFTY'S BAR & GRILLE
35       OOB-ABIA - VINO VOLO               MANGIA PIZZA

In [34]:
austin_inspections_yelp[['Restaurant Name','name']].values[0:3]

array([['AUSTIN GOLF CLUB', nan],
       ['HABESHA RESTAURANT & BAR', nan],
       ["LW - RAISING CANE'S RESTAURANTS", nan]], dtype=object)

In [42]:
type([set(x[0].split()) for x in pd.Series(austin_inspections_yelp['Restaurant Name'].values)])
[set(x[0].split()) for x in pd.Series(austin_inspections_yelp['Restaurant Name'].values)][0:5]

[{'A'}, {'H'}, {'L'}, {'D'}, {'C'}]

In [49]:
austin_inspections_yelp['Restaurant Name'] = austin_inspections_yelp['Restaurant Name'].apply(str)
austin_inspections_yelp['name'] = austin_inspections_yelp['name'].apply(str)
austin_inspections_yelp['word_overlap'] = [set(x[0].split()) & set(x[1].split()) for x in austin_inspections_yelp[['Restaurant Name','name']].values]
austin_inspections_yelp['overlap_count'] = austin_inspections_yelp['word_overlap'].str.len()
austin_inspections_yelp['anchor_words'] = [set(x[0].split()) for x in austin_inspections_yelp[['Restaurant Name']].values]
austin_inspections_yelp['anchor_words_count'] = austin_inspections_yelp['anchor_words'].str.len()

austin_inspections_yelp['diff_bt_anchor_overlap'] = austin_inspections_yelp['anchor_words_count']-austin_inspections_yelp['overlap_count']


#https://stackoverflow.com/questions/47744109/counting-a-number-of-same-words-between-two-columns-in-python-pandas

In [51]:
austin_inspections_yelp[['Restaurant Name','name','anchor_words','word_overlap','anchor_words_count','overlap_count','diff_bt_anchor_overlap']].head()

,Restaurant Name,name,anchor_words,word_overlap,anchor_words_count,overlap_count,diff_bt_anchor_overlap
0,AUSTIN GOLF CLUB,nan,"{GOLF, CLUB, AUSTIN}",{},3,0,3
1,HABESHA RESTAURANT & BAR,nan,"{&, BAR, RESTAURANT, HABESHA}",{},4,0,4
2,LW - RAISING CANE'S RESTAURANTS,nan,"{-, CANE'S, RESTAURANTS, RAISING, LW}",{},5,0,5
3,DOLLAR TREE #07241,nan,"{#07241, TREE, DOLLAR}",{},3,0,3
4,CEDAR INTERNATIONAL ACADEMY II,nan,"{ACADEMY, II, CEDAR, INTERNATIONAL}",{},4,0,4

In [186]:
print(len(austin_inspections_yelp.word_overlap[25]))
austin_inspections_yelp.word_overlap[25]

4

{'Carbon', 'Chicken', "Fresa's", 'al'}

In [223]:
print(len(austin_inspections_yelp[['Restaurant Name','name','word_overlap']].loc[austin_inspections_yelp.name!='nan']))
print(len(austin_inspections_yelp[['Restaurant Name','name','word_overlap']].loc[(austin_inspections_yelp.name!='nan') & (austin_inspections_yelp.word_overlap.str.len()>0)]))
print(len(austin_inspections_yelp[['Restaurant Name','name','word_overlap']].loc[(austin_inspections_yelp.name!='nan') & (austin_inspections_yelp.overlap_count>0)]))
austin_inspections_yelp_merge = austin_inspections_yelp.loc[(austin_inspections_yelp.name!='nan') & (austin_inspections_yelp.overlap_count>0)].reset_index(drop=True)
austin_inspections_yelp_merge.head()

21273
5786
5786

,Restaurant Name,Zip Code,Inspection Date,Score,Address,Facility ID,Process Description,letter_grade,addr_line_1,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,word_overlap,overlap_count
0,Fresa's Chicken al Carbon,78703,10/24/2019,86,"915 N LAMAR BLVD\nAUSTIN, TX 78703\n(30.274587...",10737724,Routine Inspection,B,915 N LAMAR BLVD,vyb9Ud7CT1F2kDtFOuTlVw,Fresa's Chicken al Carbon,915 N LAMAR BLVD,Austin,TX,78703,30.274465,-97.752168,3.5,404.0,1.0,"{'RestaurantsTakeOut': 'True', 'GoodForKids': ...","Mexican, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '8:0-22:0', '...","{al, Chicken, Fresa's, Carbon}",4
1,Pupuseria Usuluteca y Mas,78758,07/09/2020,93,"9306 N LAMAR BLVD\nAUSTIN, TX 78758\n(30.36226...",11620495,Routine Inspection,A,9306 N LAMAR BLVD,HgZMdXT7iPcd69MjiyZRJw,Pupuseria Usuluteca,9306 N LAMAR BLVD,Austin,TX,78753,30.362155,-97.698624,3.5,18.0,1.0,"{'HasTV': 'True', 'Ambience': '{'touristy': Fa...","Restaurants, Latin American, Salvadoran","{'Monday': '7:0-22:0', 'Tuesday': '7:0-22:0', ...","{Pupuseria, Usuluteca}",2
2,Whataburger #346,78704,10/22/2020,100,"601 BARTON SPRINGS RD\nAUSTIN, TX 78704\n(30.2...",2800311,Routine Inspection,A,601 BARTON SPRINGS RD,T3595eP9oGRF_GCOSVwUxQ,Whataburger,601 BARTON SPRINGS RD,Austin,TX,78704,30.258048,-97.750696,2.5,168.0,1.0,"{'BusinessParking': '{'garage': False, 'street...","Burgers, Fast Food, Restaurants, American (Tra...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",{Whataburger},1
3,Roaring Fork Restaurant,78701,09/17/2018,88,"701 CONGRESS AVE\nAUSTIN, TX 78701\n(30.269196...",2801929,Routine Inspection,B,701 CONGRESS AVE,AsYbCd5d7TtIZEWIL5VhOw,Roaring Fork,701 CONGRESS AVE,Austin,TX,78701,30.269054,-97.741989,4.0,1090.0,1.0,"{'WiFi': 'u'no'', 'GoodForKids': 'False', 'Alc...","American (Traditional), Bars, Restaurants, Nig...","{'Monday': '0:0-0:0', 'Tuesday': '16:0-21:0', ...","{Fork, Roaring}",2
4,La Fruta Feliz,78723,07/07/2020,71,"3124 MANOR RD\nAUSTIN, TX 78723\n(30.286615, -...",10192867,Routine Inspection,C,3124 MANOR RD,VO1ifwP9UJ7hjkswXaOrNA,La Fruta Feliz,3124 MANOR RD,Austin,TX,78723,30.286853,-97.704886,4.0,134.0,1.0,"{'WiFi': 'u'free'', 'Caters': 'True', 'BikePar...","Restaurants, Mexican","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...","{Fruta, La, Feliz}",3

In [224]:
# rechecking distribution to evaluate level of class imbalance for records that have matching yelp data
austin_inspections_yelp_merge.letter_grade.value_counts(normalize=True)

A    0.579329
B    0.319910
C    0.092119
F    0.008642
Name: letter_grade, dtype: float64